#!/usr/bin/env bash
set -euo pipefail

usage='usage: refresh-github-release.sh <release-name> <workflow-run-id> <github-repository>'
release_name=${1:?$usage}
workflow_run_id=${2:?$usage}
github_repository=${3:?$usage}

release_args=("$release_name")
if [[ "$release_name" == development ]]; then
  release_args+=(--prerelease)
fi

if gh release view "$release_name" --repo "$github_repository" --json body >/dev/null 2>&1; then
  echo "Found existing release, deleting it."
  gh release delete "$release_name" --repo "$github_repository" --yes 2>/dev/null || exit 255

  if [[ "$release_name" == development ]]; then
    gh api -X DELETE "repos/${github_repository}/git/refs/tags/${release_name}" 2>/dev/null || true
  fi
else
  echo "No existing release found."
fi

echo "Creating fresh release for this workflow..."
if gh release create "${release_args[@]}" --repo "$github_repository" --generate-notes; then
  gh release edit "$release_name" --repo "$github_repository" --notes-file <(
    gh release view "$release_name" --repo "$github_repository" --json body --jq '.body'
    printf '\n\n---\nGenerated by workflow run: %s\n' "$workflow_run_id"
  )
  echo "✓ Created fresh release"
else
  echo "Release creation failed!"
  exit 255
fi
