#!/usr/bin/env bash
set -euo pipefail

artifact_dir=${1:?usage: read-nexusmods-upload-artifact.sh <artifact-dir>}
manifest="$artifact_dir/manifest.env"
description="$artifact_dir/description.bbcode"

if [ ! -f "$manifest" ]; then
  echo "::error::Expected Nexus manifest at $manifest"
  exit 1
fi

if [ ! -f "$description" ]; then
  echo "::error::Expected Nexus description at $description"
  exit 1
fi

# The manifest is generated by prepare-nexusmods-upload-artifact.sh using shell-escaped values.
# shellcheck disable=SC1090
source "$manifest"

: "${group_id:?Nexus manifest missing group_id}"
: "${filename:?Nexus manifest missing filename}"
: "${display_name:?Nexus manifest missing display_name}"
: "${version:?Nexus manifest missing version}"
: "${archive_existing_file:?Nexus manifest missing archive_existing_file}"

archive_path="$artifact_dir/$filename"

if [ ! -f "$archive_path" ]; then
  echo "::error::Expected Nexus archive at $archive_path"
  exit 1
fi

{
  echo "group_id=$group_id"
  echo "filename=$archive_path"
  echo "display_name=$display_name"
  echo "version=$version"
  echo "archive_existing_file=$archive_existing_file"
  echo 'description<<NEXUS_DESCRIPTION_EOF'
  cat "$description"
  echo 'NEXUS_DESCRIPTION_EOF'
} >> "$GITHUB_OUTPUT"
