name: 'Corprus Crucible'
description: 'Strogg manufacturing system for Rust binaries - builds, signs, and scans releases'

inputs:
  binary_name:
    description: 'Name of the binary (without platform suffix)'
    required: true
  include_files:
    description: 'Additional files to include in archives (comma-separated)'
    required: false
    default: 'Readme.md,LICENSE'
  vt_api_key:
    description: 'VirusTotal API key (REQUIRED)'
    required: true
  github_token:
    description: 'GitHub Token (REQUIRED)'
    required: true

outputs:
  release_name:
    description: 'Name of the release (tag or development)'
    value: ${{ steps.cleanup.outputs.release_name }}

runs:
  using: composite
  steps:
    # Validate required VirusTotal API key
    - name: Validate VirusTotal API Key
      shell: bash
      run: |
        if [ -z "${{ inputs.vt_api_key }}" ]; then
          echo "::error::VirusTotal API key is required!"
          echo "Please provide vt_api_key input to this action"
          exit 1
        else
          echo "âœ… VirusTotal API key is set"
        fi

    - name: Setup Release Environment
      id: cleanup
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "release_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        else
          echo "release_name=development" >> $GITHUB_OUTPUT
          
          TODAY=$(date +%Y-%m-%d)
          
          # Get development release info with JSON
          release_info=$(gh api repos/${{ github.repository }}/releases \
            --jq '.[] | select(.name == "development" or .tag_name == "development") | {id: .id, created: .created_at, tag_name: .tag_name}' 2>/dev/null || echo "{}")
          
          if [ "$release_info" != "{}" ]; then
            release_id=$(echo "$release_info" | jq -r '.id')
            created_date=$(echo "$release_info" | jq -r '.created' | cut -d'T' -f1)
            tag_name=$(echo "$release_info" | jq -r '.tag_name')
            
            echo "Found development release: ID=$release_id, Created=$created_date"
            
            if [ "$created_date" != "$TODAY" ]; then
              echo "Release is stale (not from today). Deleting..."
              
              # Delete the release
              gh release delete "$release_id" --yes 2>/dev/null || true
              
              # Also delete the tag if it exists
              gh api -X DELETE repos/${{ github.repository }}/git/refs/tags/development 2>/dev/null || true
              
              echo "Deleted stale development release and tag"
            else
              echo "Release is from today ($TODAY), keeping it"

              gh api -X PATCH repos/${{ github.repository }}/releases/tags/development -f body="" 2>/dev/null || true
              echo "Cleared release description"
            fi
          else
            echo "No existing development release found"
          fi
        fi

    # Determine OS and set binary suffix
    - name: Determine Binary Suffix
      id: os_check
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "suffix=.exe" >> $GITHUB_OUTPUT
          echo "Binary suffix: '.exe' (Windows detected)"
        else
          echo "suffix=" >> $GITHUB_OUTPUT
          echo "Binary suffix: '' (${{ runner.os }} detected)"
        fi

    - name: Determine Build Context
      id: context
      shell: bash
      run: |
        # Auto-detect: if binary_name is a directory, build there
        if [ -d "${{ inputs.binary_name }}" ]; then
          BUILD_DIR="${{ inputs.binary_name }}"
        else
          BUILD_DIR="."
        fi

        echo "build_dir=$BUILD_DIR" >> $GITHUB_OUTPUT

    # Build steps
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: âš¡ Cache Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build Release
      shell: bash
      run: cargo build --release --manifest-path ${{ steps.context.outputs.build_dir }}/Cargo.toml

    - name: Install Cosign
      uses: sigstore/cosign-installer@main

    - name: Sign Binary
      shell: bash
      run: |
        BINARY_NAME="${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}"
        cosign sign-blob -y "${{ steps.context.outputs.build_dir }}/target/release/$BINARY_NAME" \
          --bundle "${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}.bundle"

    - name: Create Archive
      shell: bash
      run: |
        BINARY_NAME="${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}"
        ARCHIVE_NAME="${{ inputs.binary_name}}-${{ runner.os }}-${{ runner.arch }}.zip"
        
        7z a -tzip "$ARCHIVE_NAME" -r "${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}.bundle" \
          "./${{ steps.context.outputs.build_dir }}/target/release/$BINARY_NAME"
        
        IFS=',' read -ra FILES <<< "${{ inputs.include_files }}"
        for file in "${FILES[@]}"; do
          if [ -f "$file" ]; then
            7z u -tzip "$ARCHIVE_NAME" ${{ steps.context.outputs.build_dir }}/"$file"
          fi
        done

    - name: VirusTotal Scan
      id: vt_scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        update_release_body: true
        vt_api_key: ${{ inputs.vt_api_key }}
        files: ${{ steps.context.outputs.build_dir }}/target/release/${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}

    - name: Format VirusTotal Links
      id: format_vt_links
      shell: bash
      run: |
        # Extract just the filename for display
        FILENAME="${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}"

        # The vt_scan outputs.analysis is like "filename=https://virustotal.com/..."
        # Parse it to create markdown links
        if [ -n "${{ steps.vt_scan.outputs.analysis }}" ]; then
          # Convert "filename=url,filename2=url2" to markdown
          ANALYSIS_TEXT=""
          IFS=',' read -ra ENTRIES <<< "${{ steps.vt_scan.outputs.analysis }}"

          for entry in "${ENTRIES[@]}"; do
            IFS='=' read -r file url <<< "$entry"
            ANALYSIS_TEXT="${ANALYSIS_TEXT}- **${file}**: [VirusTotal Analysis](${url})"$'\n'
          done

          echo "vt_analysis<<EOF" >> $GITHUB_OUTPUT
          echo "## ðŸ” VirusTotal Scan Results" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "$ANALYSIS_TEXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "vt_analysis=" >> $GITHUB_OUTPUT
        fi

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ steps.cleanup.outputs.release_name }}
        prerelease: ${{ github.ref_type != 'tag' }}
        files: ${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}.zip
        append_body: true
        body: |
          ${{ steps.format_vt_links.outputs.vt_analysis }}

