name: 'Corprus Crucible'
description: 'Strogg manufacturing system for Rust binaries - builds, signs, and scans releases'

inputs:
  binary_name:
    description: 'Name of the binary (without platform suffix)'
    required: true
  include_files:
    description: 'Additional files to include in archives (comma-separated)'
    required: false
    default: 'Readme.md,LICENSE'
  vt_api_key:
    description: 'VirusTotal API key (REQUIRED)'
    required: true
  github_token:
    description: 'GitHub Token (REQUIRED)'
    required: true
  release_name:
    description: 'Name of the release (tag or development)'
    required: true
  # cargo_token:
  #   description: 'If provided, the token is used to publish the target app to crates.io'
  #   required: false
  #   default: ''

runs:
  using: composite
  steps:
    # Validate required VirusTotal API key
    - name: Validate VirusTotal API Key
      shell: bash
      run: |
        if [ -z "${{ inputs.vt_api_key }}" ]; then
          echo "::error::VirusTotal API key is required!"
          echo "Please provide vt_api_key input to this action"
          exit 1
        else
          echo "✅ VirusTotal API key is set"
        fi

    - name: Determine Binary Suffix
      id: os_check
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          echo "suffix=.exe" >> $GITHUB_OUTPUT
          echo "Binary suffix: '.exe' (Windows detected)"
        else
          echo "suffix=" >> $GITHUB_OUTPUT
          echo "Binary suffix: '' (${{ runner.os }} detected)"
        fi

    - name: Determine Build Context
      id: context
      shell: bash
      run: |
        # Auto-detect: if binary_name is a directory, build there
        if [ -d "${{ inputs.binary_name }}" ]; then
          BUILD_DIR="${{ inputs.binary_name }}"
        else
          BUILD_DIR="."
        fi

        echo "build_dir=$BUILD_DIR" >> $GITHUB_OUTPUT

    # Build steps
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: ⚡ Cache Dependencies
      uses: actions/cache@v4
      if: github.event_name != 'pull_request'
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build Release
      shell: bash
      run: cargo test --all-targets --all-features --manifest-path ${{ steps.context.outputs.build_dir }}/Cargo.toml -- --show-output && cargo build --release --manifest-path ${{ steps.context.outputs.build_dir }}/Cargo.toml

    # - name: Cargo Publish
    #   if: ${{ inputs.cargo_token }} != '' && ${{ inputs.release_name }} != 'development'
    #   shell: bash
    #   run: cargo publish --manifest-path ${{ steps.context.outputs.build_dir }}/Cargo.toml --token ${{ inputs.cargo_token }}

    - name: Install Cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@main

    - name: Sign Binary
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        BINARY_NAME="${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}"
        cosign sign-blob -y "${{ steps.context.outputs.build_dir }}/target/release/$BINARY_NAME" \
          --bundle "${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}.bundle"

    - name: Create Archive
      shell: bash
      if: github.event_name != 'pull_request'
      run: |
        BINARY_NAME="${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}"
        ARCHIVE_NAME="${{ inputs.binary_name}}-${{ runner.os }}-${{ runner.arch }}.zip"
        
        INCLUDE_FILES=(
          "./${{ steps.context.outputs.build_dir }}/target/release/$BINARY_NAME"
          "${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}.bundle"
        )
        
        if [ -n "${{ inputs.include_files }}" ]; then
          IFS=',' read -ra USER_FILES <<< "${{ inputs.include_files }}"
          for file in "${USER_FILES[@]}"; do
            if [ -f "./${{ steps.context.outputs.build_dir }}/$file" ]; then
              INCLUDE_FILES+=("./${{ steps.context.outputs.build_dir }}/$file")
            fi
          done
        fi

        # Create archive with all files at once
        7z a -tzip "$ARCHIVE_NAME" "${INCLUDE_FILES[@]}"

    - name: VirusTotal Scan
      if: github.event_name != 'pull_request'
      id: vt_scan
      uses: crazy-max/ghaction-virustotal@v4
      with:
        update_release_body: true
        vt_api_key: ${{ inputs.vt_api_key }}
        files: ${{ steps.context.outputs.build_dir }}/target/release/${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}

    - name: Format VirusTotal Links
      if: github.event_name != 'pull_request'
      id: format_vt_links
      shell: bash
      run: |
        # Extract just the filename for display
        FILENAME="${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}"

        # The vt_scan outputs.analysis is like "filename=https://virustotal.com/..."
        # Parse it to create markdown links
        if [ -n "${{ steps.vt_scan.outputs.analysis }}" ]; then
          # Convert "filename=url,filename2=url2" to markdown
          ANALYSIS_TEXT=""
          IFS=',' read -ra ENTRIES <<< "${{ steps.vt_scan.outputs.analysis }}"

          for entry in "${ENTRIES[@]}"; do
            IFS='=' read -r file url <<< "$entry"
            ANALYSIS_TEXT="${ANALYSIS_TEXT}- [${FILENAME} on VirusTotal](${url})"$'\n'
          done

          echo "vt_analysis=${ANALYSIS_TEXT}" >> $GITHUB_OUTPUT
        else
          echo "vt_analysis=" >> $GITHUB_OUTPUT
        fi

    - name: Upload to GitHub Release
      if: github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ inputs.release_name }}
        prerelease: ${{ github.ref_type != 'tag' }}
        files: ${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}.zip
        append_body: true
        body: |
          ${{ steps.format_vt_links.outputs.vt_analysis }}

    - name: Upload artifact (for PRs)
      if: github.event_name == 'pull_request'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.binary_name }}-${{ runner.os }}-${{ runner.arch }}
        path: ./${{ steps.context.outputs.build_dir }}/target/release/${{ inputs.binary_name }}${{ steps.os_check.outputs.suffix }}
        retention-days: 7

