name: Create DreamWeave Release

on:
  workflow_call:
    outputs:
      release_name:
        description: "Release name generated based on tag or branch."
        value: ${{ jobs.ensure-fresh-release.outputs.release_name }}

jobs:
  ensure-fresh-release:
    name: Create & Log Release
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.setup.outputs.release_name }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: DreamWeave-MP/StroggForge
          ref: v40
          path: .stroggforge

      - name: Setup Release Environment
        id: setup
        env:
          RELEASE_IS_TAG: ${{ startsWith(github.ref, 'refs/tags/') }}
          RELEASE_REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ "$RELEASE_IS_TAG" == true ]]; then
            RELEASE_NAME="$RELEASE_REF_NAME"
          else
            RELEASE_NAME=development
          fi

          echo "release_name=$RELEASE_NAME" >> "$GITHUB_OUTPUT"

      - name: Ensure Fresh Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ steps.setup.outputs.release_name }}
          WORKFLOW_RUN_ID: ${{ github.run_id }}
          RELEASE_REPOSITORY: ${{ github.repository }}
        run: bash .stroggforge/scripts/shared/refresh-github-release.sh "$RELEASE_NAME" "$WORKFLOW_RUN_ID" "$RELEASE_REPOSITORY"
