name: Create DreamWeave Release

on:
  workflow_call:
    outputs:
      release_name:
        description: "Release name generated based on tag or branch."
        value: ${{ jobs.ensure-fresh-release.outputs.release_name }}

jobs:
  ensure-fresh-release:
    name: Create & Log Release
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.setup.outputs.release_name }}

    steps:
      - uses: actions/checkout@v6
      - uses: actions/checkout@v6
        with:
          repository: DreamWeave-MP/StroggForge
          ref: v35
          path: .stroggforge

      - name: Setup Release Environment
        id: setup
        run: |
          if ${{ startsWith(github.ref, 'refs/tags/') }}; then
            RELEASE_NAME="${{ github.ref_name }}"
          else
            RELEASE_NAME=development
          fi

          echo "release_name=$RELEASE_NAME" >> "$GITHUB_OUTPUT"

      - name: Ensure Fresh Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash .stroggforge/scripts/shared/refresh-github-release.sh "${{ steps.setup.outputs.release_name }}" "${{ github.run_id }}" "${{ github.repository }}"
