name: Notify DreamWeave Ecosystem

on:
  workflow_call:
    secrets:
      DW_BOT_PAT:
        required: true

    inputs:
      aur_package_name:
        type: string
        required: false
        default: ''
      dependent_repo_names:
        type: string
        required: false
        default: ''

jobs:
  notify-dependents:
    name: Notify Dependent Repositories
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          repository: DreamWeave-MP/StroggForge
          ref: v19
          path: .stroggforge

      - name: Create Update Issue
        env:
          GH_TOKEN: ${{ secrets.DW_BOT_PAT }}
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: bash .stroggforge/scripts/shared/create-dependent-update-issues.sh '${{ inputs.dependent_repo_names }}' '${{ inputs.aur_package_name }}'
